version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always 
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/src/static
      - ./config/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
  web:
    build: .
    restart: always 
    container_name: django_container

    env_file:
      - django.env
    depends_on:
      - db
    volumes:
      - ./static:/src/static
      - ./src:/src
    expose:
      - "80"
  db:
    image: mysql:latest
    restart: always 
    container_name: MYSQL_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: fagottino
    volumes:
    - ~/code/mysql/datadir:/var/lib/mysql 