version: '2'
networks:
  fagottino_net:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    volumes:
      - ./src:/src
      - ./config/nginx/mydjango.conf:/etc/nginx/nginx.conf
      - ./static:/src/static
      - ./config/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - fagottino_net
  web:
    build: .
    restart: always 
    container_name: django_container
    env_file:
      - django.env
    depends_on:
      - db
    volumes:
      - ./static:/src/static
      - ./src:/src
    networks:
      - fagottino_net
  db:
    image: mysql:latest
    restart: always 
    container_name: MYSQL_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: fagottino
    volumes:
    - ~/code/mysql/datadir:/var/lib/mysql
    networks:
      - fagottino_net
    