version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: NGINXDOCKERNAME
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: DJANGOXDOCKERNAME
    entrypoint: /src/prep-env.sh
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
  db:
    image: mysql:latest
    container_name: MSQLDOCKERNAME
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: fagottino
    # volumes:
    # - .msqldata:/var/lib/mysql  #had this working initially but seems to get corrupt need to look into more
